layout: sidebar
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by: pushed
  # sort_by options:
  #   - pushed
  #   - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:
    # - repo-name

# social_media:
  # behance: your_username
  # dribbble: your_username
  # facebook: your_username
  # hackerrank: your_username
  # instagram: your_username
  # keybase: your_username
  # linkedin: your_username
  # mastodon: your_username
  # medium: your_username
  # stackoverflow: your_user_id
  # telegram: your_username
  # twitter: your_username
  # unsplash: your_username
  # vk: your_username
  # website: http://your_website_url
  # youtube: your_username

topics:
  - name: Hacking
    web_url: https://www.bsi-fuer-buerger.de/BSIFB/DE/Risiken/Hacker/hacker_node.html
    image_url: https://pixabay.com/get/53e1d0424f51af14f1dc8460da29317e1536dae15b5674_640.jpg

  - name: Internet Privacy
    web_url: https://en.wikipedia.org/wiki/Internet_privacy
    image_url: https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Internet_map_1024_-_transparent%2C_inverted.png/480px-Internet_map_1024_-_transparent%2C_inverted.png

  - name: Security and Privacy
    web_url: https://www.inf.uni-hamburg.de/inst/ab/snp/home.html
    image_url: https://assets.rrz.uni-hamburg.de/assets/uhh-logo-4ec3691b46570436d95977e2c0c368646d0c24d722425dd674f48b1c44585e81.svg
